### ISSUE TITLE
options for configuration

### ISSUE THREAD

**Issue by z0xyz** [small-tech/catts#10]
The documentation doesn't contain any tweaking options or configuration file to customize the behavior of catts .
I've tried to look up the plugin at dconf-editor as the fork's [predecessor had its settings configured this way](                            https://elementaryos.stackexchange.com/a/24336
) had its settings altered this way , but without any luck .
The bare minimum amount of options to be enabled are the icon size (which is gigantic by default) , and a toggle for the window caption visibility .

**Comment by aral** [comment]
Hello and thank you for reporting this issue.

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

If this is still a problem for you, you can reach their issue tracker at https://github.com/elementary/gala/issues
