### ISSUE TITLE
alt-tab sometimes stuck

### ISSUE THREAD

**Issue by minhdanh** [small-tech/catts#12]
Sometimes when I press alt-tab to switch between running applications, the switcher appear but just stuck, without switching to the selected application. If then I press alt-tab again, the switcher will disappear but not to my wanted application.

It looks like whenever I press the alt button for a little bit longer and then press tab, this will happen.

I have my keyboard repeat rate customized, and it looks like this:
![image](https://user-images.githubusercontent.com/4865412/134770106-76803c3e-50ca-4dc1-a475-63ec2ee73d6c.png)

P.S: Actually I had this problem with the original switcher too. So not sure if this is a problem with catts.

**Comment by aral** [comment]
Hello and thank you for reporting this issue.

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

If this is still a problem for you, you can reach their issue tracker at https://github.com/elementary/gala/issues
