### ISSUE TITLE
Uninstall instructions?

### ISSUE THREAD

**Issue by brachiocephalic** [small-tech/catts#14]
Enjoy this task switcher much more than what shipped with elementaryOS. However, it'd be nice to know how to revert to the stock task switcher, just in case.. Never know if some issue pops up or whatever. I am not overly technical thus some instruction in a readme file or some script to remove would be appreciated.

**Comment by ChildishGiant** [comment]
If you installed using [krisives/elementary-os-extras](https://github.com/krisives/elementary-os-extras) it should be as simple as `sudo apt remove elementary-catts`. If you installed using the instructions on the readme it seems that `sudo rm /usr/lib/x86_64-linux-gnu/gala/plugins/libgala-catts.so` and then a reboot or `gala --replace &` should do the job

**Comment by aral** [comment]
Hi folks,

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

You can reach their issue tracker at https://github.com/elementary/gala/issues
