### ISSUE TITLE
Security error. File has been tampered with. DO NOT PROCEED!

### ISSUE THREAD

**Issue by davidpeach** [small-tech/catts#6]
Clicked the copy paste icon for step 1 and pasted into terminal. Downloaded fine.

Clicked the copy paste icon for step 2 and pasted into terminal.

Full message:
```
bash -lic "test \"\$(sha256sum /tmp/libgala-catts.so)\" = 'c73ce1c713fbf8b7e261c20d70268580fa6f7d1bd5a70a4e1ba5ea50d20206fc  /tmp/libgala-catts.so' && echo 'Download OK.' || echo 'Security error. File has been tampered with. DO NOT PROCEED!'"
bash: !': event not found
```

**Comment by aral** [comment]
Ah, I forgot that you have to escape exclamation marks for Bash. (Even though the command is always run in bash regardless of the shell you’re using, the command itself needs the exclamation mark escaped if you’re running it in Bash.)

Should be fixed in 881b723

**Comment by davidpeach** [comment]
Works for me now. Is Beautiful.

**Comment by aral** [comment]
Yay, thanks @davidpeach; appreciate your help. Closing this now.
