### ISSUE TITLE
Cancel switching by pressing Escape

### ISSUE THREAD

**Issue by ckruse** [small-tech/catts#7]
It should be possible to cancel switching applications by pressing escape. Currently it just ignores the escape key.

**Comment by orta** [comment]
This does seem to be working for me (if you press alt + escape)

**Comment by ckruse** [comment]
For me it switches to the currently selected application. Canceling would mean, I stay at the previous application.

**Comment by aral** [comment]
Thank you for reporting this :)

David has already implemented this as part of his draft pull request for Gala and I’m just about to implement his commit here also. Will release a new binary once I’m done implementing all of David’s improvements (the ones so far have been code improvements but this is the first one that actually affects functionality so a new binary release is called for).

**Comment by aral** [comment]
Right, folks, version 1.0.1, now released, includes this fix :)

To upgrade, please follow the installation instructions again.

**Comment by ckruse** [comment]
Thanks for your work!

**Comment by aral** [comment]
Thanks @ckruse, but this is all @davidmhewitt ;) (And he’s already improved the seven-year-old fork of a fork of a fork of a fork codebase with his work to pull it into Gala yesterday. I’ve mirrored most of his changes back here but my hope is that Catts as a separate entity won’t be required for much longer.) :)

**Comment by ckruse** [comment]
well, then thanks for your work, too, @davidmhewitt! ❤️

Yeah, I saw your Issue, @aral – getting it merged to Gala would indeed be really cool!
