### ISSUE TITLE
Font LoOkS LiKe ThIs

### ISSUE THREAD

**Issue by nevillepark** [small-tech/catts#8]
Hi! Really enjoying the app. However, the font is weirdly rendered, making the text look lopsided. For example, the letters `h`, `i`, `m` and `n` appear to have a higher baseline than the others. (This happens regardless of the text size set in Desktop → Appearance; the screenshots here use the largest setting so it's clearer.)

Please let me know if there's any system information you need that would help.

![SyStEm SeTtInGs](https://user-images.githubusercontent.com/16054979/131235248-34982a1d-6c94-46dd-b8f1-a877e22ef7a0.png)
![ScReEnShOtS](https://user-images.githubusercontent.com/16054979/131235249-936a8dd7-a851-4e23-b0f6-1fefa9405ce3.png)

**Comment by aral** [comment]
Ah, that’s odd – thank you for reporting this. Any ideas @davidmhewitt?

**Comment by aral** [comment]
Quick update: 

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

If this is still a problem for you, you can reach their issue tracker at https://github.com/elementary/gala/issues
