### ISSUE TITLE
Please add a version git tag number

### ISSUE THREAD

**Issue by krisives** [small-tech/catts#9]
I'm adding `catts` to a recipe on Launchpad that automatically grabs the latest code from this GitHub repository and builds the packages. Usually what I do when packaging something up is make use of a feature that grabs the package version from the latest tag, where the tag is usually something like `0.1.2`. However, this repository does not have any tags or from what I can tell any version numbers. Upstream (`gala-alt-tab-plus`) did also not seem to have any version numbers, so you'll have to pick some starting number.

For the time being in the package recipe I have hardcoded the version number of `0.0.1` so that when you pick a version number it will "override" the one I've set.

Also, for the package name I selected `elementary-catts` and for the copyright I set it to match your info from the GitHub profile.

The goal for the PPA that I am making is to include many out-of-the-box improvements to elementaryOS. Currently it includes `catts` and the *Monitor* app that is not compatible with Flatpak sandboxing, but there are likely a few other areas where the community disagrees a bit with how stock elementaryOS is implemented.

**Comment by krisives** [comment]
The packaging is complete and seems to be working (minus that version number issue). It can be used/tested via:

```
sudo add-apt-repository -r ppa:elementary-extras/ppa
sudo apt install elementary-catts
```

Let me know if you have any questions or want anything changed.

**Comment by aral** [comment]
@krisives How neat, thank you :) 

Regarding tags: bad Aral, lazy! Will fix.

(I’m going to make a third release incorporating @davidmhewitt’s recent commit with HiDPI support and a few other tweaks. Before I do, I’ll retroactively tag the correct commits as 1.0.0 and 1.0.1 and the latest one as 1.0.2.)

**Comment by aral** [comment]
@krisives Just a quick update: I just tagged versions 1.0.0 and 1.0.1. I’m going to hold off on 1.0.2 until I’ve had a chance to test it a bit more. But will be tagging releases from here on in.

Also, I just tried adding the repository and installing via your instructions and I get:

```
E: Unable to locate package elementary-catt
```

Any ideas?

**Comment by aral** [comment]
@krisives Question: the `.so` installed by apt is ~44kb whereas the one I build is ~71kb.

In the [elementary-extra readme](https://git.launchpad.net/elementary-extras/tree/README.md), you state installing `software-properties-common` prior to elementary-extras. Is something being dynamically linked from there in the apt version? (Sorry, I haven’t worked with apt packaging so I don’t know the internals.)

If so, should the complete installation instructions via apt be:

```shell
sudo apt install software-properties-common
sudo add-apt-repository ppa:elementary-extras/ppa
sudo apt install elementary-catts
```

**Comment by krisives** [comment]
> In the elementary-extras readme, you state installing software-properties-common prior to elementary-extras. Is something being dynamically linked from there in the apt version? (Sorry, I haven’t worked with apt packaging so I don’t know the internals.)

No, the `software-properties-common` is the base package that provides the `add-apt-repository` command. It's a convenience command that simply writes a file to `/etc/apt/sources.d/`, ensures a signing key is setup correctly and runs `apt update` so that the packages from the added PPA are easily available.

Also, yes the commands you listed are the correct commands to add the PPA and install `elementary-catts`. This is exactly what I did on my system.

**Comment by aral** [comment]
> No, the `software-properties-common` is the base package that provides the `add-apt-repository` command. It's a convenience command that simply writes a file to `/etc/apt/sources.d/`, ensures a signing key is setup correctly and runs `apt update` so that the packages from the added PPA are easily available.

Ah, y’know what, I actually knew that (or at least I ran through those steps myself while setting up 5 and then 6 again). Thanks! ;) 

So what accounts for the size difference? (If nothing else, I’d love to reduce the size of my build too.) :)

**Comment by krisives** [comment]
My guess is that it's related to the build flags that were used by Launchpad which are typically very aggressive with optimization and debug symbol stripping. Here is the log from when Launchpad built it using the git recipe:

https://launchpadlibrarian.net/556031871/buildlog_ubuntu-focal-amd64.elementary-catts_0.0.2-0~202108291815~ubuntu6.1_BUILDING.txt.gz

Which looks like the underlying compile command ends up being something like this:

```
/usr/bin/cc -DWNCK_I_KNOW_THIS_IS_UNSTABLE -Dgala_catts_EXPORTS -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC   -mfpmath=sse -msse -msse2 -pthread -I/usr/include/gala -I/usr/include/mutter-6 -I/usr/include/mutter-6/clutter -I/usr/include/json-glib-1.0 -I/usr/include/mutter-6/cogl -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/granite -I/usr/include/gee-0.8 -I/usr/include/libwnck-3.0 -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/gsettings-desktop-schemas -o CMakeFiles/gala-catts.dir/src/Main.c.o   -c /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/Main.c
```

Also, no idea what the `WNCK_I_KNOW_THIS_IS_UNSTABLE` stuff is. I know i didn't put it there!

Your best bet at replicating exactly what Launchpad is doing during it's build process is probably going to be to run something similar to it's `cmake` build command:

```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_AUTOGEN_VERBOSE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu ..
```

Probably the only important part there is the `-DCMAKE_BUILD_TYPE=None` part, which IIRC is similar to `-DCMAKE_BUILD_TYPE=Release`.

**Comment by aral** [comment]
@krisives Thanks for the all the info, appreciate it. Will have a proper look when I’m back from holiday. PS. Just had to remove the elementary-extras PPA as I was getting an error that it was no longer signed. Did something change?

**Comment by krisives** [comment]
I changed the PPA from `elementary-extras/ppa` to `elementary-extras/stable` and there is also an `elementary-extras/testing` so that before I release anything to `stable` it can be tested.

**Comment by aral** [comment]
Ah, cool, thanks. Will include the stable branch in the instructions.

**Comment by aral** [comment]
Quick update: I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

For future reference, their issue tracker is at https://github.com/elementary/gala/issues
